# -*- coding: utf-8 -*-
"""Assignment #1:  Numeric Variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H7UDjEMQiwWIiEQtZHX9w6RYq6TMC0sb
"""

while True:
    program_choice = input("Please enter which calculation you would like to perform. 'c' for change, 't' for temperature, or 's' to stop the program.\n ")

    # choice c is for the change calculator
    if program_choice == 'c':
        f_user_cost = float(input('Enter the total cost: \n'))
        f_tendered_amount = float(input('Enter the amount tendered: \n'))

        # Calculate the difference between the tendered amount and the total cost to find the amount of change that is needed
        dollar_cost = f_tendered_amount - f_user_cost

        # Calculate the number of bills needed

        #hundred dollar bills
        hundred_dollar_bills = int(dollar_cost // 100)
        dollar_cost %= 100
        print(hundred_dollar_bills, "hundred dollar bill(s)")
        #fifty dollar bills
        fifty_dollar_bills = int(dollar_cost // 50)
        dollar_cost %= 50
        print(fifty_dollar_bills, "fifty dollar bill(s)")
        #twenty dollar bills
        twenty_dollar_bills = int(dollar_cost // 20)
        dollar_cost %= 20
        print(twenty_dollar_bills, "twenty dollar bill(s)")
        #ten dollar bills
        ten_dollar_bills = int(dollar_cost // 10)
        dollar_cost %= 10
        print(ten_dollar_bills, "ten dollar bill(s)")
        #five dollar bills
        five_dollar_bills = int(dollar_cost // 5)
        dollar_cost %= 5
        print(five_dollar_bills, "five dollar bill(s)")
        #one dollar bills
        one_dollar_bills = int(dollar_cost // 1)
        dollar_cost %= 1
        print(one_dollar_bills, "one dollar bill(s)")

        # Calculate the remaining change in cents
        cent_cost = float(dollar_cost * 100)

        #quarters
        quarters = cent_cost // 25
        cent_cost %= 25
        print(quarters, "quarters")
        #dimes
        dimes = cent_cost // 10
        cent_cost %= 10
        print(dimes, "dimes")
        # nickels
        nickels = cent_cost // 5
        cent_cost %= 5
        print(nickels, "nickels")

        #pennies (need to round to nearest whole number or else 1 will = 0)
        pennies = round(cent_cost * 1)
        print(pennies, "pennies")

        # this is the condition for the while loop, so that the user can continue the calculations without exiting
        money_again = input("Would you like to perform another calculation? ('y' or 'n') \n")

        #if user dosen't enter 'y', the program will end.
        if money_again != 'y':
            break

    # choice #t is for the temperature converter
    elif program_choice == 't':
        print("\n\n Welcome to the temperature converter calculator.")

        starting_temp = float(input("Enter the temperature you would like to convert with: \n"))
        temp_scale = input("Enter the scale you are starting with: ('c' for Celsius, 'f' for Fahrenheit, 'k' for Kelvin)")

        # these are if else statements to perform calculations based on the user's starting scale and desired ending scales (order of operations)
        if temp_scale == 'c':
            convert_scale = input("Enter the scale you would like to convert to: ")
            if convert_scale == 'f':
                c_convert = (starting_temp * (9/5) + 32)
                print(c_convert)
            elif convert_scale == 'k':
                c_convert = (starting_temp + 273)
                print(c_convert)

        elif temp_scale == 'f':
            convert_scale = input("Enter the scale you would like to convert to:")
            if convert_scale == 'c':
                f_convert = (starting_temp - 32) * (5/9)
                print(f_convert)
            elif convert_scale == 'k':
                f_convert = (starting_temp - 32) * (5/9) + 273
                print(f_convert)

        elif temp_scale == 'k':
            convert_scale = input("Enter the scale you would like to convert to:")
            if convert_scale == 'c':
                k_convert = starting_temp - 273
                print(k_convert)
            elif convert_scale == 'f':
                k_convert = (starting_temp - 273) * (9/5) + 32
                print(k_convert)

        # this is another while loop condition so that the user can continue with the temperature calculations without exiting
        temp_again = input("Would you like to make another calculation? ('y' or 'n')\n")
        #if user doent enter 'y' the program will end
        if temp_again != 'y':
            break

    # if the user enters 's' this will exit the program entirely
    elif program_choice == 's':
        break

    # this is in case the user enters something other than 'c' 't' or 's'. they will then have to restart the program
    else:
        print("You have entered an invalid choice. Please try again.\n")